
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 2048-Game
  region: us-east-1

managedNodeGroups:
- name: 2048_game
  instanceType: m5.large
  desiredCapacity: 3
  spot: true
  